baseURL: https://www.travelexperiencias.com
disablePathToLower: true
languageCode: es
title: Travelexperiencias
theme: gochowdown
googleAnalytics:
defaultcontentlanguage: es
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: John Doe
  description: Recipes used by the Doe family
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: true
  hidecopyright: true
  showNavTitle: false            # Boolean: show site title in nav bar
  custom_css:
    - style.css
menu:
  main:
    - name: Inicio
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags
